### ISSUE TITLE
The Filtering commands don't work anymore in Mavericks

### ISSUE THREAD

**Issue by deegeenl** [textmate/text.tmbundle#11]
Both in TextMate 2.0a and TextMate 1.5.11, the Text/Filtering commands don't do anything anymore since I upgraded to Mavericks: The 'Copy Matching Lines into New Document' command should show a prompt for entering a pattern, but it doesn't do that. 

 I've looked at the scripts, pretty sure it's due to the migration to Ruby 2.0, but these are just bash scripts calling ruby and python inside, so not clear to me what the fix is.

**Comment by giucal** [comment]
Observing the same behaviour in version `2.0-beta.11.9` (and the previous nighty build as well) for commands prompting for something.

**Comment by sorbits** [comment]
I am unable to reproduce. Can you provide detailed steps to reproduce to be sure we are testing the same thing?

https://github.com/textmate/textmate/wiki/Writing-Bug-Reports

**Comment by giucal** [comment]
- Open a new buffer and type in some garbage.
- Select, for instance, *Bundles* &rarr; *Text* &rarr; *Encryption* &rarr; *AES Encrypt Document / Selection With Password…*

Nothing happens: no prompt is displayed, no error messages.

I looked at the logs and found this:

    16/07/16 15:51:37,269 TextMate[505]: showNib:withParameters:andInitialValues:dynamicClasses:modal:center:async: failed loading nib: /Users/Giuseppe/Library/Application Support/TextMate/Managed/Bundles/Bundle Support.tmbundle/Support/shared/nibs/RequestSecureString.nib. If you are using a .xib file, it must be compiled.

Analogous error for *Filtering* &rarr; *Copy Matching Lines into New Document*:

    16/07/16 16:05:48,632 TextMate[1586]: showNib:withParameters:andInitialValues:dynamicClasses:modal:center:async: failed loading nib: /Users/Giuseppe/Library/Application Support/TextMate/Managed/Bundles/Bundle Support.tmbundle/Support/shared/nibs/RequestString.nib. If you are using a .xib file, it must be compiled.

**Comment by sorbits** [comment]
What OS version are you using?

/cc @rdwampler

**Comment by giucal** [comment]
El Capitan (10.11.5)

**Comment by rdwampler** [comment]
Have you edit that .nib recently? I suspect it may actually be a .xib. Can you check the contents of ` /Users/Giuseppe/Library/Application Support/TextMate/Managed/Bundles/Bundle Support.tmbundle/Support/shared/nibs/RequestSecureString.nib`? If it's a .nib, it should be directory containing the file `keyedobjects.nib`.

**Comment by giucal** [comment]
No, I've not edited it. Same problem also from a newly created account. Anyway, `RequestSecureString.nib` contains these three files:

    classes.nib      info.nib         keyedobjects.nib

**Comment by rdwampler** [comment]
@sorbits I think we should revert the changes to the dialog plugins. I can't reproduce the error, but my only guess is that .nib is not being recognized as a file package. Probably should just check if the file nib/keyedobjects.nib exists.

**Comment by sorbits** [comment]
OK, I have reverted the change and pushed beta 11.12.

I think your hunch is correct, most likely `nib` files are defined by Xcode.app, so any user without the developer tools will see this problem.

@giucal By any chance, does your system “lack” developer tools (Xcode)?

**Comment by giucal** [comment]
Beta 11.12 works as expected.

@sorbits Partly: I just have command-line tools.
